services:
  api:
    build: .
    container_name: insurance-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      - MONGO_URI=mongodb://mongodb:27017/insurance_assessment

    depends_on:
      - mongodb

    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: insurance-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: unless-stopped

volumes:
  mongo_data: